language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: NIs891ppMzacOFAj6UWRHOZQ4igutbPlVuaDUsSR3Q3ZW807SkxjMrvMU2XldIUZt9bEOLf4zkl4ICq5cXJXFwdSn8CfY5RoKXtKwvoTUocm1Ef15JFTXT1eLA/W3l5QcFq7E01CQRmqn8ooCj7+C/ZrpHj40WVC9uHQOmgFKNqrtreSq+z3knFg9HNMJ5Dfx4E6vJfKSKJuspVjgCRm9c2gAa1nwfLmXKZVu2bKvhysR8HQomeOToyV78X9wV0G/Z918vZxrhbWZobFuqqYO1KrjXCbi87B2OTUcTU7hLgQEN7ifzKynPKs1sYVSvqPTaQaYpeUWXUuMUjHfPPaCp/iavpe4G1x4zVL+idFdv1WwZPFHhJcUDmV3B3Mwt+yzaUotNfD7+Mem4rbu/R0Vv/SxenVwbRjGONsJkdiwhP93aG8gySidN3e27AY2zqF64NZhl57+d5eoTOcYdtW0NrliKJBSInlDtDVUyYQkNfmVRFqdfUFSVYNfNRyEfQH/sBM9YbsiNurKr3tCpyTws82js63lRO4PmC3/KlK0W8h7wBx9elK0yEDW77inIJLs0MysrCkNw3DDx/M2cbRzzulJIj2mWcfUlO8KPmjpEZAJh/TUooH5db/pmv/0E1gN3LO6TMbYX+dsjzL8gkkdRSw5mw5uPXoPXfpnde+hRQ=
  app: most-view-video
  on:
    repo: wangmeng255/most-view-video
    branch: dev
